authorName: CTA
experimentName: nni_searcher
trialConcurrency: 1
maxExecDuration: 100h
maxTrialNum: 50
trainingServicePlatform: local
# The path to Search Space
searchSpacePath: search_space.json
logDir: /home/lab402-3090/Desktop/An/NAS-nni/nni/nni-experiment
useAnnotation: false
debug: true
tuner:
  builtinTunerName: TPE
  classArgs:
    #choice: maximize, minimize
    optimize_mode: maximize
# The path and the running command of trial
trial:
  command: python3 nni_searcher.py
  codeDir: .
  gpuNum: 1
localConfig:
   useActiveGpu: true
   gpuIndices: 0
   maxTrialNumPerGpu: 1
